## This is a pair of functions that cache the inverse of a matrix

## This function creats a special "matrix" object that can cache its inverse, 
##it returns a list of four fucntions: set(),get(),setSolve(),getSolve() and two
##data objects: x and i


makeCacheMatrix <- function(x = matrix()) {
        
        i <- NULL
        
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setSolve <- function(Solve) i <<- Solve
        getSolve <- function() i
        
        list(set = set, get = get,
             setSolve = setSolve,
             getSolve = getSolve)
}


## This function computes the inverse of the special "matrix" returned by makeCacheMatrix above.
## Note that the input x is a list and it should be generated by calling makeCacheMatrix above

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        i<- x$getSolve()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setSolve(i)
        i
}


